"""
core/attachments/store.py - SQLite persistence for Attachment metadata
(Sprint 2.7 / Wave 1 / Worker 2).

Owns database/attachments.db EXCLUSIVELY ("satu .db, satu pemilik modul" -
docs/database.md), the same convention already used by
core/artifacts/store.py (artifacts.db), core/selection/store.py
(selection_context.db), core/model_store.py (model_router.db), and
core/persona/engine.py (persona.db).

A dedicated database is warranted here (not reuse of chat_sessions.db or
artifacts.db) because attachment metadata has its own query shape that
neither existing table supports without conflating unrelated ownership:

    - chat_sessions.db (chat_turns) stores conversational content, not
      file metadata, and has no columns for mime_type/size/storage
      reference/attachment status; abusing steps_json/content for this
      would mix concerns core/chat_sessions.py never signed up to own.
    - artifacts.db is owned by core/artifacts and only ever represents
      AIRA-GENERATED files (ArtifactStatus has no "user_upload"/"external"
      concept, and Artifact has no message_id/lifecycle for validation
      failures pre-storage). Attachments must also represent files that
      were never generated by AIRA at all.

This module stores METADATA ONLY (mirrors core/artifacts/store.py exactly:
the actual bytes live in the AIRA Workspace via core.filesystem, NEVER
inside this database).
"""
from __future__ import annotations

import json
import sqlite3
import threading
import time
from contextlib import closing
from pathlib import Path
from typing import Optional

from core.attachments.models import Attachment

BASE_DIR = Path(__file__).resolve().parents[2]  # AIRA_ECOSYSTEM/
DEFAULT_DB_FILE = BASE_DIR / "database" / "attachments.db"

SCHEMA_SQL = """
CREATE TABLE IF NOT EXISTS attachments (
    id TEXT PRIMARY KEY,
    session_id TEXT,
    message_id TEXT,
    name TEXT NOT NULL,
    mime_type TEXT NOT NULL,
    size INTEGER NOT NULL DEFAULT 0,
    storage_reference TEXT,
    source TEXT NOT NULL DEFAULT 'user_upload',
    status TEXT NOT NULL DEFAULT 'pending',
    created_at REAL NOT NULL,
    updated_at REAL NOT NULL,
    metadata TEXT NOT NULL DEFAULT '{}'
);
CREATE INDEX IF NOT EXISTS idx_attachments_session ON attachments(session_id);
CREATE INDEX IF NOT EXISTS idx_attachments_message ON attachments(message_id);
CREATE INDEX IF NOT EXISTS idx_attachments_status ON attachments(status);
"""


class AttachmentStore:

    def __init__(self, db_path: Optional[Path] = None):
        self.db_path = Path(db_path) if db_path else DEFAULT_DB_FILE
        self.db_path.parent.mkdir(parents=True, exist_ok=True)
        self._lock = threading.Lock()
        self._init_db()

    def _connect(self) -> sqlite3.Connection:
        conn = sqlite3.connect(self.db_path, timeout=10)
        conn.row_factory = sqlite3.Row
        return conn

    def _init_db(self) -> None:
        with self._lock, closing(self._connect()) as conn:
            conn.executescript(SCHEMA_SQL)
            conn.commit()

    # ------------------------------------------------------------ write

    def save(self, attachment: Attachment) -> Attachment:
        """Insert or update (id is the natural key - re-saving the same id
        overwrites; used e.g. when a pending attachment becomes available,
        or a status transition happens)."""
        with self._lock, closing(self._connect()) as conn:
            conn.execute("""
                INSERT INTO attachments
                    (id, session_id, message_id, name, mime_type, size,
                     storage_reference, source, status, created_at,
                     updated_at, metadata)
                VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
                ON CONFLICT(id) DO UPDATE SET
                    session_id = excluded.session_id,
                    message_id = excluded.message_id,
                    name = excluded.name,
                    mime_type = excluded.mime_type,
                    size = excluded.size,
                    storage_reference = excluded.storage_reference,
                    source = excluded.source,
                    status = excluded.status,
                    updated_at = excluded.updated_at,
                    metadata = excluded.metadata
            """, (
                attachment.id, attachment.session_id, attachment.message_id,
                attachment.name, attachment.mime_type, attachment.size,
                attachment.storage_reference, attachment.source, attachment.status,
                attachment.created_at, attachment.updated_at,
                json.dumps(attachment.metadata, ensure_ascii=False, default=str),
            ))
            conn.commit()

        return attachment

    def delete(self, attachment_id: str) -> bool:
        """Hard delete of the METADATA ROW. Removing the underlying file
        (if any) is the engine's job (core/attachments/engine.py) - this
        store only ever touches its own table, same boundary as
        core/artifacts/store.py::ArtifactStore.delete()."""
        with self._lock, closing(self._connect()) as conn:
            cursor = conn.execute("DELETE FROM attachments WHERE id = ?", (attachment_id,))
            conn.commit()
            return cursor.rowcount > 0

    # ------------------------------------------------------------- read

    def get(self, attachment_id: str) -> Optional[Attachment]:
        with closing(self._connect()) as conn:
            row = conn.execute("SELECT * FROM attachments WHERE id = ?", (attachment_id,)).fetchone()

        return self._row_to_attachment(row) if row else None

    def list(
        self,
        session_id: Optional[str] = None,
        message_id: Optional[str] = None,
        status: Optional[str] = None,
        source: Optional[str] = None,
        include_deleted: bool = False,
    ) -> list[Attachment]:
        conditions, params = [], []

        if session_id is not None:
            conditions.append("session_id = ?")
            params.append(session_id)
        if message_id is not None:
            conditions.append("message_id = ?")
            params.append(message_id)
        if status is not None:
            conditions.append("status = ?")
            params.append(status)
        elif not include_deleted:
            conditions.append("status != 'deleted'")
        if source is not None:
            conditions.append("source = ?")
            params.append(source)

        where = f"WHERE {' AND '.join(conditions)}" if conditions else ""

        with closing(self._connect()) as conn:
            rows = conn.execute(
                f"SELECT * FROM attachments {where} ORDER BY created_at DESC", params,
            ).fetchall()

        return [self._row_to_attachment(r) for r in rows]

    def count(self, session_id: Optional[str] = None) -> int:
        with closing(self._connect()) as conn:
            if session_id is None:
                row = conn.execute("SELECT COUNT(*) AS c FROM attachments").fetchone()
            else:
                row = conn.execute(
                    "SELECT COUNT(*) AS c FROM attachments WHERE session_id = ?", (session_id,),
                ).fetchone()

        return int(row["c"])

    @staticmethod
    def _row_to_attachment(row: sqlite3.Row) -> Attachment:
        data = dict(row)
        try:
            data["metadata"] = json.loads(data.get("metadata") or "{}")
        except (json.JSONDecodeError, TypeError):
            data["metadata"] = {}
        return Attachment.from_dict(data)


_store_singleton: Optional[AttachmentStore] = None
_store_lock = threading.Lock()


def get_attachment_store() -> AttachmentStore:
    global _store_singleton
    if _store_singleton is None:
        with _store_lock:
            if _store_singleton is None:
                _store_singleton = AttachmentStore()
    return _store_singleton

    def get_by_storage_reference(
        self, storage_reference: str, include_deleted: bool = False,
    ) -> Optional[Attachment]:
        """Reverse lookup: workspace path -> Attachment (workspace <-> conversation
        integration, core/workspace_links). None if no attachment owns this path."""
        if not storage_reference:
            return None

        query = "SELECT * FROM attachments WHERE storage_reference = ?"
        params: list = [storage_reference]

        if not include_deleted:
            query += " AND status != 'deleted'"

        query += " ORDER BY created_at DESC LIMIT 1"

        with closing(self._connect()) as conn:
            row = conn.execute(query, params).fetchone()

        return self._row_to_attachment(row) if row else None